module CoolToJS {

    export enum Action {
        Shift, Reduce, Accept, None
    }

    export interface ParseTableEntry {
        action: Action;
        nextState?: number;
        productionIndex?: number;
    }

    export var slr1ParseTable: Array<Array<ParseTableEntry>> = [
		/* state 0 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.None, nextState: 2 }, null, null, null, null, null, null, null, { action: Action.None, nextState: 1 }],
		/* state 1 */[{ action: Action.Accept }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 2 */[{ action: Action.Reduce, productionIndex: 1 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 3 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.None, nextState: 2 }, null, null, null, null, null, null, null, { action: Action.None, nextState: 4 }],
		/* state 3 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 4 */[{ action: Action.Reduce, productionIndex: 2 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 5 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 6 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 7 }, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 6 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 8 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 7 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 11 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.None, nextState: 10 }, { action: Action.None, nextState: 9 }, null, null, null, null],
		/* state 8 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 12 }, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 9 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null /* s13,r4 */, null, null, null, null, null, null, null, null, null, null, null],
		/* state 10 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 3 }, null, null, null, null, null, null, null, null, null, null, null],
		/* state 11 */[null, { action: Action.Shift, nextState: 14 }, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 15 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 12 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 11 }, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 17 }, null, null, null, null, null, { action: Action.None, nextState: 10 }, { action: Action.None, nextState: 16 }, null, null, null, null],
		/* state 13 */[{ action: Action.Reduce, productionIndex: 7 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 7 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 14 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 20 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.None, nextState: 19 }, { action: Action.None, nextState: 18 }, null, null],
		/* state 15 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 21 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 16 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null /* s22,r4 */, null, null, null, null, null, null, null, null, null, null, null],
		/* state 17 */[{ action: Action.Reduce, productionIndex: 6 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 6 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 18 */[null, null, null, null, null, null, null, null, null, null /* s23,r9 */, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 19 */[null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 8 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 20 */[null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 24 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 21 */[null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 25 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 22 */[{ action: Action.Reduce, productionIndex: 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 5 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 23 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 26 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 24 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 27 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 25 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 28 }, null, null, null, null, null, null, null],
		/* state 26 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 43 }, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 27 */[null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 12 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 28 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 11 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 29 */[null, { action: Action.Shift, nextState: 55 }, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, null, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, null, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Shift, nextState: 54 }, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, null, { action: Action.Reduce, productionIndex: 41 }, null, null, { action: Action.Reduce, productionIndex: 41 }, null, null, { action: Action.Reduce, productionIndex: 41 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 41 }, null, null, null, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, null, { action: Action.Reduce, productionIndex: 41 }, null, null, null, null, { action: Action.Reduce, productionIndex: 41 }, { action: Action.Reduce, productionIndex: 41 }, null, null, null, null, null, null, null, null, null, null],
		/* state 30 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 56 }, null, null, null, null, null, null, null],
		/* state 31 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 57 }, null, null, null, null, null, null, null],
		/* state 32 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 59 }, { action: Action.None, nextState: 58 }, null, null, null, null, null, null],
		/* state 33 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 60 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 34 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 61 }, null, null, null, null, null, null, null],
		/* state 35 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 62 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 36 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 63 }, null, null, null, null, null, null, null],
		/* state 37 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 64 }, null, null, null, null, null, null, null],
		/* state 38 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 65 }, null, null, null, null, null, null, null],
		/* state 39 */[null, null, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, null, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, null, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, null, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, null, { action: Action.Reduce, productionIndex: 42 }, null, null, { action: Action.Reduce, productionIndex: 42 }, null, null, { action: Action.Reduce, productionIndex: 42 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 42 }, null, null, null, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, null, { action: Action.Reduce, productionIndex: 42 }, null, null, null, null, { action: Action.Reduce, productionIndex: 42 }, { action: Action.Reduce, productionIndex: 42 }, null, null, null, null, null, null, null, null, null, null],
		/* state 40 */[null, null, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, null, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, null, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, null, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, null, { action: Action.Reduce, productionIndex: 43 }, null, null, { action: Action.Reduce, productionIndex: 43 }, null, null, { action: Action.Reduce, productionIndex: 43 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 43 }, null, null, null, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, null, { action: Action.Reduce, productionIndex: 43 }, null, null, null, null, { action: Action.Reduce, productionIndex: 43 }, { action: Action.Reduce, productionIndex: 43 }, null, null, null, null, null, null, null, null, null, null],
		/* state 41 */[null, null, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, null, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, null, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, null, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, null, { action: Action.Reduce, productionIndex: 44 }, null, null, { action: Action.Reduce, productionIndex: 44 }, null, null, { action: Action.Reduce, productionIndex: 44 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 44 }, null, null, null, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, null, { action: Action.Reduce, productionIndex: 44 }, null, null, null, null, { action: Action.Reduce, productionIndex: 44 }, { action: Action.Reduce, productionIndex: 44 }, null, null, null, null, null, null, null, null, null, null],
		/* state 42 */[null, null, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, null, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, null, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, null, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, null, { action: Action.Reduce, productionIndex: 45 }, null, null, { action: Action.Reduce, productionIndex: 45 }, null, null, { action: Action.Reduce, productionIndex: 45 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 45 }, null, null, null, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, null, { action: Action.Reduce, productionIndex: 45 }, null, null, null, null, { action: Action.Reduce, productionIndex: 45 }, { action: Action.Reduce, productionIndex: 45 }, null, null, null, null, null, null, null, null, null, null],
		/* state 43 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 66 }, null, null, null, null, null, null, null],
		/* state 44 */[null, { action: Action.Shift, nextState: 67 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 45 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 68 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 46 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 69 }, null, null, null, null, null, null, null],
		/* state 47 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 70 }, null, null, null, null, null, null, null],
		/* state 48 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 71 }, null, null, null, null, null, null, null],
		/* state 49 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 72 }, null, null, null, null, null, null, null],
		/* state 50 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 73 }, null, null, null, null, null, null, null],
		/* state 51 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 74 }, null, null, null, null, null, null, null],
		/* state 52 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 75 }, null, null, null, null, null, null, null],
		/* state 53 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 76 }, null, null, null, null, null, null, null],
		/* state 54 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 77 }, null, null, null, null, null, null, null],
		/* state 55 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 59 }, { action: Action.None, nextState: 78 }, null, null, null, null, null, null],
		/* state 56 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 79 }, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 57 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 80 }, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 58 */[null, null, { action: Action.Reduce, productionIndex: 14 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null /* s81,r14 */, null, null, null, null, null, null, null, null, null, null, null],
		/* state 59 */[null, null, { action: Action.Reduce, productionIndex: 13 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 13 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 60 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 82 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 61 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 83 }, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 62 */[null, null, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, null, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, null, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, null, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, null, { action: Action.Reduce, productionIndex: 29 }, null, null, { action: Action.Reduce, productionIndex: 29 }, null, null, { action: Action.Reduce, productionIndex: 29 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 29 }, null, null, null, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, null, { action: Action.Reduce, productionIndex: 29 }, null, null, null, null, { action: Action.Reduce, productionIndex: 29 }, { action: Action.Reduce, productionIndex: 29 }, null, null, null, null, null, null, null, null, null, null],
		/* state 63 */[null, null, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Reduce, productionIndex: 30 }, null, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Shift, nextState: 44 }, { action: Action.Reduce, productionIndex: 30 }, null, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Reduce, productionIndex: 30 }, null, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Reduce, productionIndex: 30 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 30 }, null, null, { action: Action.Reduce, productionIndex: 30 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 30 }, null, null, null, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Reduce, productionIndex: 30 }, null, { action: Action.Reduce, productionIndex: 30 }, null, null, null, null, { action: Action.Reduce, productionIndex: 30 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 64 */[null, null, { action: Action.Reduce, productionIndex: 39 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 39 }, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 39 }, null, null, { action: Action.Reduce, productionIndex: 39 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 39 }, null, null, null, { action: Action.Reduce, productionIndex: 39 }, { action: Action.Reduce, productionIndex: 39 }, null, { action: Action.Reduce, productionIndex: 39 }, null, null, null, null, { action: Action.Reduce, productionIndex: 39 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 65 */[null, null, { action: Action.Shift, nextState: 84 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 66 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 85 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 67 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 59 }, { action: Action.None, nextState: 86 }, null, null, null, null, null, null],
		/* state 68 */[null, null, null, null, null, null, null, { action: Action.Shift, nextState: 87 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 69 */[null, null, { action: Action.Reduce, productionIndex: 31 }, { action: Action.Shift, nextState: 48 }, { action: Action.Reduce, productionIndex: 31 }, null, { action: Action.Reduce, productionIndex: 31 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 31 }, { action: Action.Reduce, productionIndex: 31 }, null, { action: Action.Reduce, productionIndex: 31 }, { action: Action.Reduce, productionIndex: 31 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 31 }, null, null, { action: Action.Reduce, productionIndex: 31 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 31 }, null, null, null, { action: Action.Reduce, productionIndex: 31 }, { action: Action.Reduce, productionIndex: 31 }, null, { action: Action.Reduce, productionIndex: 31 }, null, null, null, null, { action: Action.Reduce, productionIndex: 31 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 70 */[null, null, { action: Action.Reduce, productionIndex: 32 }, { action: Action.Shift, nextState: 48 }, { action: Action.Reduce, productionIndex: 32 }, null, { action: Action.Reduce, productionIndex: 32 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 32 }, { action: Action.Reduce, productionIndex: 32 }, null, { action: Action.Reduce, productionIndex: 32 }, { action: Action.Reduce, productionIndex: 32 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 32 }, null, null, { action: Action.Reduce, productionIndex: 32 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 32 }, null, null, null, { action: Action.Reduce, productionIndex: 32 }, { action: Action.Reduce, productionIndex: 32 }, null, { action: Action.Reduce, productionIndex: 32 }, null, null, null, null, { action: Action.Reduce, productionIndex: 32 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 71 */[null, null, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Reduce, productionIndex: 33 }, null, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Shift, nextState: 44 }, { action: Action.Reduce, productionIndex: 33 }, null, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Reduce, productionIndex: 33 }, null, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Reduce, productionIndex: 33 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 33 }, null, null, { action: Action.Reduce, productionIndex: 33 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 33 }, null, null, null, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Reduce, productionIndex: 33 }, null, { action: Action.Reduce, productionIndex: 33 }, null, null, null, null, { action: Action.Reduce, productionIndex: 33 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 72 */[null, null, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Reduce, productionIndex: 34 }, null, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Shift, nextState: 44 }, { action: Action.Reduce, productionIndex: 34 }, null, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Reduce, productionIndex: 34 }, null, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Reduce, productionIndex: 34 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 34 }, null, null, { action: Action.Reduce, productionIndex: 34 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 34 }, null, null, null, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Reduce, productionIndex: 34 }, null, { action: Action.Reduce, productionIndex: 34 }, null, null, null, null, { action: Action.Reduce, productionIndex: 34 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 73 */[null, null, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Reduce, productionIndex: 35 }, null, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Shift, nextState: 44 }, { action: Action.Reduce, productionIndex: 35 }, null, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Reduce, productionIndex: 35 }, null, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Reduce, productionIndex: 35 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 35 }, null, null, { action: Action.Reduce, productionIndex: 35 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 35 }, null, null, null, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Reduce, productionIndex: 35 }, null, { action: Action.Reduce, productionIndex: 35 }, null, null, null, null, { action: Action.Reduce, productionIndex: 35 }, { action: Action.Reduce, productionIndex: 35 }, null, null, null, null, null, null, null, null, null, null],
		/* state 74 */[null, null, { action: Action.Reduce, productionIndex: 36 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 36 }, { action: Action.Reduce, productionIndex: 36 }, null, { action: Action.Reduce, productionIndex: 36 }, { action: Action.Reduce, productionIndex: 36 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 36 }, null, null, { action: Action.Reduce, productionIndex: 36 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 36 }, null, null, null, { action: Action.Reduce, productionIndex: 36 }, { action: Action.Reduce, productionIndex: 36 }, null, { action: Action.Reduce, productionIndex: 36 }, null, null, null, null, { action: Action.Reduce, productionIndex: 36 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 75 */[null, null, { action: Action.Reduce, productionIndex: 37 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 37 }, { action: Action.Reduce, productionIndex: 37 }, null, { action: Action.Reduce, productionIndex: 37 }, { action: Action.Reduce, productionIndex: 37 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 37 }, null, null, { action: Action.Reduce, productionIndex: 37 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 37 }, null, null, null, { action: Action.Reduce, productionIndex: 37 }, { action: Action.Reduce, productionIndex: 37 }, null, { action: Action.Reduce, productionIndex: 37 }, null, null, null, null, { action: Action.Reduce, productionIndex: 37 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 76 */[null, null, { action: Action.Reduce, productionIndex: 38 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 38 }, { action: Action.Reduce, productionIndex: 38 }, null, { action: Action.Reduce, productionIndex: 38 }, { action: Action.Reduce, productionIndex: 38 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 38 }, null, null, { action: Action.Reduce, productionIndex: 38 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 38 }, null, null, null, { action: Action.Reduce, productionIndex: 38 }, { action: Action.Reduce, productionIndex: 38 }, null, { action: Action.Reduce, productionIndex: 38 }, null, null, null, null, { action: Action.Reduce, productionIndex: 38 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 77 */[null, null, { action: Action.Reduce, productionIndex: 20 }, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Reduce, productionIndex: 20 }, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Reduce, productionIndex: 20 }, null, null, { action: Action.Reduce, productionIndex: 20 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 20 }, null, null, null, { action: Action.Reduce, productionIndex: 20 }, { action: Action.Reduce, productionIndex: 20 }, null, { action: Action.Reduce, productionIndex: 20 }, null, null, null, null, { action: Action.Reduce, productionIndex: 20 }, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 78 */[null, null, null /* s88,r14 */, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 14 }, null, null, null, null, null, null, null, null, null, null, null],
		/* state 79 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 89 }, null, null, null, null, null, null, null],
		/* state 80 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 90 }, null, null, null, null, null, null, null],
		/* state 81 */[null, null, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, null, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, null, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, null, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, null, { action: Action.Reduce, productionIndex: 26 }, null, null, { action: Action.Reduce, productionIndex: 26 }, null, null, { action: Action.Reduce, productionIndex: 26 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 26 }, null, null, null, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, null, { action: Action.Reduce, productionIndex: 26 }, null, null, null, null, { action: Action.Reduce, productionIndex: 26 }, { action: Action.Reduce, productionIndex: 26 }, null, null, null, null, null, null, null, null, null, null],
		/* state 82 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 91 }, null, null, null, null, null, null, null],
		/* state 83 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 93 }, null, null, null, null, null, null, null, null, null, null, { action: Action.None, nextState: 92 }, null, null, null, null, null, null, null, null, null],
		/* state 84 */[null, null, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, null, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, null, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, null, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, null, { action: Action.Reduce, productionIndex: 40 }, null, null, { action: Action.Reduce, productionIndex: 40 }, null, null, { action: Action.Reduce, productionIndex: 40 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 40 }, null, null, null, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, null, { action: Action.Reduce, productionIndex: 40 }, null, null, null, null, { action: Action.Reduce, productionIndex: 40 }, { action: Action.Reduce, productionIndex: 40 }, null, null, null, null, null, null, null, null, null, null],
		/* state 85 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 10 }, null, null, null, null, null, null, null, null, null, null, null],
		/* state 86 */[null, null, null /* s94,r14 */, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 14 }, null, null, null, null, null, null, null, null, null, null, null],
		/* state 87 */[null, { action: Action.Shift, nextState: 95 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 88 */[null, null, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, null, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, null, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, null, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, null, { action: Action.Reduce, productionIndex: 23 }, null, null, { action: Action.Reduce, productionIndex: 23 }, null, null, { action: Action.Reduce, productionIndex: 23 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 23 }, null, null, null, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, null, { action: Action.Reduce, productionIndex: 23 }, null, null, null, null, { action: Action.Reduce, productionIndex: 23 }, { action: Action.Reduce, productionIndex: 23 }, null, null, null, null, null, null, null, null, null, null],
		/* state 89 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, { action: Action.Shift, nextState: 96 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 90 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 97 }, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 91 */[null, null, { action: Action.Reduce, productionIndex: 27 }, null /* s48,r27 */, null /* s46,r27 */, null, null /* s47,r27 */, null /* s44,r27 */, null /* s49,r27 */, null, { action: Action.Reduce, productionIndex: 27 }, null /* s51,r27 */, null, null /* s52,r27 */, null /* s53,r27 */, null, null /* s45,r27 */, null, null, { action: Action.Reduce, productionIndex: 27 }, null, null, { action: Action.Reduce, productionIndex: 27 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 27 }, null, null, null, { action: Action.Reduce, productionIndex: 27 }, { action: Action.Reduce, productionIndex: 27 }, null, { action: Action.Reduce, productionIndex: 27 }, null, null, null, null, { action: Action.Reduce, productionIndex: 27 }, null /* s50,r27 */, null, null, null, null, null, null, null, null, null, null],
		/* state 92 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 98 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 93 */[null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 99 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 94 */[null, null, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, null, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, null, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, null, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, null, { action: Action.Reduce, productionIndex: 21 }, null, null, { action: Action.Reduce, productionIndex: 21 }, null, null, { action: Action.Reduce, productionIndex: 21 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 21 }, null, null, null, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, null, { action: Action.Reduce, productionIndex: 21 }, null, null, null, null, { action: Action.Reduce, productionIndex: 21 }, { action: Action.Reduce, productionIndex: 21 }, null, null, null, null, null, null, null, null, null, null],
		/* state 95 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 59 }, { action: Action.None, nextState: 100 }, null, null, null, null, null, null],
		/* state 96 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 101 }, null, null, null, null, null, null, null],
		/* state 97 */[null, null, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, null, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, null, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, null, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, null, { action: Action.Reduce, productionIndex: 25 }, null, null, { action: Action.Reduce, productionIndex: 25 }, null, null, { action: Action.Reduce, productionIndex: 25 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 25 }, null, null, null, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, null, { action: Action.Reduce, productionIndex: 25 }, null, null, null, null, { action: Action.Reduce, productionIndex: 25 }, { action: Action.Reduce, productionIndex: 25 }, null, null, null, null, null, null, null, null, null, null],
		/* state 98 */[null, null, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, null, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, null, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, null, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, null, { action: Action.Reduce, productionIndex: 28 }, null, null, { action: Action.Reduce, productionIndex: 28 }, null, null, { action: Action.Reduce, productionIndex: 28 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 28 }, null, null, null, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, null, { action: Action.Reduce, productionIndex: 28 }, null, null, null, null, { action: Action.Reduce, productionIndex: 28 }, { action: Action.Reduce, productionIndex: 28 }, null, null, null, null, null, null, null, null, null, null],
		/* state 99 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 102 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 100 */[null, null, null /* s103,r14 */, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 14 }, null, null, null, null, null, null, null, null, null, null, null],
		/* state 101 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, null, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, { action: Action.Shift, nextState: 104 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 102 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 105 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 103 */[null, null, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, null, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, null, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, null, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, null, { action: Action.Reduce, productionIndex: 22 }, null, null, { action: Action.Reduce, productionIndex: 22 }, null, null, { action: Action.Reduce, productionIndex: 22 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 22 }, null, null, null, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, null, { action: Action.Reduce, productionIndex: 22 }, null, null, null, null, { action: Action.Reduce, productionIndex: 22 }, { action: Action.Reduce, productionIndex: 22 }, null, null, null, null, null, null, null, null, null, null],
		/* state 104 */[null, null, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, null, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, null, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, null, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, null, { action: Action.Reduce, productionIndex: 24 }, null, null, { action: Action.Reduce, productionIndex: 24 }, null, null, { action: Action.Reduce, productionIndex: 24 }, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 24 }, null, null, null, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, null, { action: Action.Reduce, productionIndex: 24 }, null, null, null, null, { action: Action.Reduce, productionIndex: 24 }, { action: Action.Reduce, productionIndex: 24 }, null, null, null, null, null, null, null, null, null, null],
		/* state 105 */[null, { action: Action.Shift, nextState: 38 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 34 }, null, null, null, { action: Action.Shift, nextState: 42 }, null, { action: Action.Shift, nextState: 30 }, null, null, { action: Action.Shift, nextState: 39 }, { action: Action.Shift, nextState: 36 }, { action: Action.Shift, nextState: 33 }, null, null, { action: Action.Shift, nextState: 35 }, { action: Action.Shift, nextState: 37 }, { action: Action.Shift, nextState: 29 }, null, null, { action: Action.Shift, nextState: 40 }, null, { action: Action.Shift, nextState: 41 }, null, { action: Action.Shift, nextState: 31 }, { action: Action.Shift, nextState: 32 }, null, null, null, null, { action: Action.None, nextState: 106 }, null, null, null, null, null, null, null],
		/* state 106 */[null, null, null, { action: Action.Shift, nextState: 48 }, { action: Action.Shift, nextState: 46 }, null, { action: Action.Shift, nextState: 47 }, { action: Action.Shift, nextState: 44 }, { action: Action.Shift, nextState: 49 }, null, { action: Action.Shift, nextState: 107 }, { action: Action.Shift, nextState: 51 }, null, { action: Action.Shift, nextState: 52 }, { action: Action.Shift, nextState: 53 }, null, { action: Action.Shift, nextState: 45 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 50 }, null, null, null, null, null, null, null, null, null, null],
		/* state 107 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 18 }, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Shift, nextState: 93 }, null, null, null, null, null, null, null, null, null, null, { action: Action.None, nextState: 108 }, null, null, null, null, null, null, null, null, null],
		/* state 108 */[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { action: Action.Reduce, productionIndex: 19 }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
		/* state 109 */[null]
    ];

    export var productions: Array<{ popCount: number; reduceResult: SyntaxKind }> = [
        // 0: $accept -> Program $end
        { popCount: 2, reduceResult: null },

        // 1: Program -> Class
        { popCount: 1, reduceResult: SyntaxKind.Program },

        // 2: Program -> Class Program
        { popCount: 2, reduceResult: SyntaxKind.Program },

        // 3: FeatureList -> Feature
        { popCount: 1, reduceResult: SyntaxKind.FeatureList },

        // 4: FeatureList -> FeatureList
        { popCount: 1, reduceResult: SyntaxKind.FeatureList },

        // 5: Class -> ClassKeyword TypeIdentifier InheritsKeyword TypeIdentifier { FeatureList }
        { popCount: 7, reduceResult: SyntaxKind.Class },

        // 6: Class -> ClassKeyword TypeIdentifier InheritsKeyword TypeIdentifier { }
        { popCount: 6, reduceResult: SyntaxKind.Class },

        // 7: Class -> ClassKeyword TypeIdentifier { FeatureList }
        { popCount: 5, reduceResult: SyntaxKind.Class },

        // 8: FormalList -> Formal
        { popCount: 1, reduceResult: SyntaxKind.FormalList },

        // 9: FormalList -> FormalList
        { popCount: 1, reduceResult: SyntaxKind.FormalList },

        // 10: Feature -> ObjectIdentifier ( FormalList : TypeIdentifier { Expression }
        { popCount: 8, reduceResult: SyntaxKind.Feature },

        // 11: Feature -> ObjectIdentifier : TypeIdentifier <- Expression
        { popCount: 5, reduceResult: SyntaxKind.Feature },

        // 12: Formal -> ObjectIdentifier : TypeIdentifier
        { popCount: 3, reduceResult: SyntaxKind.Formal },

        // 13: ExpressionList -> Expression
        { popCount: 1, reduceResult: SyntaxKind.ExpressionList },

        // 14: ExpressionList -> ExpressionList
        { popCount: 1, reduceResult: SyntaxKind.ExpressionList },

        // 15: LocalVariableDeclarationList -> ObjectIdentifier : TypeIdentifier
        { popCount: 3, reduceResult: SyntaxKind.LocalVariableDeclarationList },

        // 16: LocalVariableDeclarationList -> ObjectIdentifier : TypeIdentifier <- Expression
        { popCount: 5, reduceResult: SyntaxKind.LocalVariableDeclarationList },

        // 17: LocalVariableDeclarationList -> ObjectIdentifier : TypeIdentifier , LocalVariableDeclarationList
        { popCount: 5, reduceResult: SyntaxKind.LocalVariableDeclarationList },

        // 18: CaseOption -> ObjectIdentifier : TypeIdentifier => Expression ;
        { popCount: 6, reduceResult: SyntaxKind.CaseOption },

        // 19: CaseOption -> ObjectIdentifier : TypeIdentifier => Expression ; CaseOption
        { popCount: 7, reduceResult: SyntaxKind.CaseOption },

        // 20: Expression -> ObjectIdentifier <- Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 21: Expression -> Expression . ( ExpressionList )
        { popCount: 5, reduceResult: SyntaxKind.Expression },

        // 22: Expression -> Expression @ TypeIdentifier . ( ExpressionList )
        { popCount: 7, reduceResult: SyntaxKind.Expression },

        // 23: Expression -> ObjectIdentifier ( ExpressionList )
        { popCount: 4, reduceResult: SyntaxKind.Expression },

        // 24: Expression -> IfKeyword Expression ThenKeyword Expression ElseKeyword Expression FiKeyword
        { popCount: 7, reduceResult: SyntaxKind.Expression },

        // 25: Expression -> WhileKeyword Expression LoopKeyword Expression PoolKeyword
        { popCount: 5, reduceResult: SyntaxKind.Expression },

        // 26: Expression -> { ExpressionList }
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 27: Expression -> LetKeyword LocalVariableDeclaration InKeyword Expression
        { popCount: 4, reduceResult: SyntaxKind.Expression },

        // 28: Expression -> CaseKeyword Expression OfKeyword CaseOption EsacKeyword
        { popCount: 5, reduceResult: SyntaxKind.Expression },

        // 29: Expression -> NewKeyword TypeIdentifier
        { popCount: 2, reduceResult: SyntaxKind.Expression },

        // 30: Expression -> IsvoidKeyword Expression
        { popCount: 2, reduceResult: SyntaxKind.Expression },

        // 31: Expression -> Expression + Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 32: Expression -> Expression - Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 33: Expression -> Expression * Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 34: Expression -> Expression / Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 35: Expression -> Expression ~ Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 36: Expression -> Expression < Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 37: Expression -> Expression <= Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 38: Expression -> Expression = Expression
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 39: Expression -> NotKeyword Expression
        { popCount: 2, reduceResult: SyntaxKind.Expression },

        // 40: Expression -> ( Expression )
        { popCount: 3, reduceResult: SyntaxKind.Expression },

        // 41: Expression -> ObjectIdentifier
        { popCount: 1, reduceResult: SyntaxKind.Expression },

        // 42: Expression -> Integer
        { popCount: 1, reduceResult: SyntaxKind.Expression },

        // 43: Expression -> String
        { popCount: 1, reduceResult: SyntaxKind.Expression },

        // 44: Expression -> TrueKeyword
        { popCount: 1, reduceResult: SyntaxKind.Expression },

        // 45: Expression -> FalseKeyword
        { popCount: 1, reduceResult: SyntaxKind.Expression },

    ];
} 